#!/bin/bash

./smallsh <<'___EOF___'
echo BEGINNING TEST SCRIPT
echo
echo --------------------
echo comment
#THIS COMMENT SHOULD DO NOTHING
echo
echo
echo --------------------
echo return dir content using ls
ls
echo
echo
echo --------------------
echo ls out junk
ls > junk
echo
echo
echo --------------------
echo cat junk
cat junk
echo
echo
echo --------------------
echo wc in junk
wc < junk
echo
echo
echo --------------------
echo wc in junk out junk2; cat junk2
wc < junk > junk2
cat junk2
echo
echo
echo --------------------
echo test -f badfile returns error value of 1, note extraneous &
test -f badfile
status &
echo
echo
echo --------------------
echo wc in badfile return Cannot Open
wc < badfile
echo
echo
echo --------------------
echo badfile return Command Not Found
badfile
echo
echo
echo --------------------
echo sleep 100 background returns process ID of sleeper
sleep 100 &
echo
echo
echo --------------------
echo pkill -signal SIGTERM sleep returns pid of kiled process & signal number
pkill sleep
echo
echo
echo --------------------
echo sleep 1 background returns pid of bg process & exit value when done
sleep 1 &
sleep 1
echo
echo
echo --------------------
echo pwd
pwd
echo
echo
echo --------------------
echo cd
cd
echo
echo
echo --------------------
echo pwd returns HOME dir
pwd
echo
echo
echo --------------------
echo mkdir testdir$$
mkdir testdir$$
echo
echo
echo --------------------
echo cd testdir$$
cd testdir$$
echo
echo
echo --------------------
echo pwd returns newly created dir
pwd
echo --------------------
echo Testing foreground-only mode returns fg entry & exit text & ~5 seconds between times
kill -SIGTSTP $$
date
sleep 5 &
date
kill -SIGTSTP $$
echo END OF TEST SCRIPT
exit
___EOF___
